jdk:
- oraclejdk8
language: scala
scala:
- 2.11.8
- 2.12.2
sudo: required
env:
  global:
  - secure: R4CtPpPtcAbxTvhTXZXVOP0xtXw6fl7QkN7SPwp8OWsWzY2W1kl8V75P1r+470lrojipiw5LhR0DCk0NvLxtmrZRajw0+qJHm18D8DiAZXWbdp777IQvbZor/GHRy0WiqdcidcuxEuV0uF/pvAdJUx6G+1dyD9/CnZcVOtAFzWaJU9UDEO4rVZygDQkeBPN/CDO/tYGfikVXsws1+4iz2CHXEwat0xBPlYD2uWepvMkzvnNL5J+c2nGOXB1Ge5wySOTLbDAoK6rOgcMGVZxg/8AdMZfv0y9vtGmi5tvvs03rDXHItoC5YEG7ohWfU+2mTpPWF3+wSzDBbdD6PhEO20tS5qjVWYiU8KCqgOHKtb5tNHjuQXZriu3BSo2pgFnA5Q/kdd9j28bxgH5YbNpm3BYRVzGKKTwdL3fVb6wmdXsclgs0HSJCp1gl24zartt0m9kliTbvmMJK1uh4itOr8SX46IRv2jXS25CAIAaZ91tsp06bNI+YpLYZVDIox7qQ3xqAS59sBF9UYjYH1PJ8Q5bdYBPfbfQqAEM+PTBokSo0dA79OEPdx2oatRmYmmXl7AtrLvrgQZBXv61XQGbsEC7/ulYcEjHrNrwPMoFB+ATEc6/HFwwMmpdWDZbTmBTLytoIruMXoishy4ebn1BsZjELe5cxTo8uFpumu7Ow454=
  - secure: EjQd9WAPYeTkFCztlBKU+vEjkk5R4JIbmHuGtUUcvoQpN8FOIgLqEvTKtkTeNXo7aaLvvzUypIqXjjPd4GaTXB3sv0CqCEClsm49a55SzlgE8uthz5/tmXLQOPmEdHGluwlfhvBHreFi9sIEz0R0CGg+C/YAUagDpNC5AMsgo+ntFIpuNaoVlUTAeHmyyaK6IGUx4P3TPyJjmZwlIRSfEEcqo0zTkRxkai3Enr1XnitDzghe0XoFme+rkqHqTA6X2d8E3YPHZd+RV+IjCGTxlfRFk4kYQ9OIVckBWep2h2w1aXC+sPu/kw7RCwIcH6fSR94wuRmanClCnKr81sBLB0gcPB4eN23A0GnDGEHFcSNpdWd7gFEVr6nivXoR4v25Ng5pHVUQY9kprqjXmd8uF/L0MARmtbjBjsZtQknVZVZ9MBICL3mdeKbOCwejbptXN7nQPUO7387v5OHMz8BFbJMqRcjtTIRaNcu3KdtWu+urYwkzalEuYjZ8ZBUm7Fx26nHJevPe7TBxLqShVqVm52HsZS9nfDYavgzi0EayPnMaPVx06DgXQAaHXhqPjrNAuyu5+Y1ZfkwTBS0Wm+36/ADwPIxTmlaWjxRzNaD/CRthVTauuTTdoCHtuzW4jw3dgSBRmt+10FFVVegbW+0uiI1o5AXIdSW0rnWoly9DcjA=
script:
- SBT_OPTS=-Xmx3g sbt clean coverage test coverageReport -Denv.type=test && SBT_OPTS=-Xmx3g sbt coverageAggregate
after_success:
- SBT_OPTS=-Xmx3g sbt coveralls
- bash scripts/publish.sh
