name: Unit Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

#      - name: Auth with Google Cloud Platform
#        id: auth
#        uses: google-github-actions/auth@v0
#        with:
#          credentials_json: ${{ secrets.GCP_SA_KEY }}
#          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Start pubsub emulator
        run: |
          gcloud --quiet components install pubsub-emulator
          gcloud --quiet beta emulators pubsub start --project="broad-dsp-gcr-public" &

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          java-version: "adopt@1.17"

      - name: Compile and check scalafmt
        run: |
          sbt -Denv.type=test clean "test:compile" scalafmtCheckAll

      - name: Build and test
        run: |
          sbt -Dfile.encoding=UTF-8 clean coverage +test -l org.broadinstitute.dsde.workbench.google.tags.RedRing coverageReport
          
          

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup Cache
        uses: coursier/cache-action@v5

      - name: Cache resources
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
